package com.advanceinv.advancedinvisibility;

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.events.ListenerPriority;
import com.comphenix.protocol.events.PacketAdapter;
import com.comphenix.protocol.events.PacketEvent;
import com.comphenix.protocol.wrappers.WrappedDataValue;
import org.bukkit.Sound;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;

import java.util.ArrayList;
import java.util.List;

public class PacketListeners {

    private final AdvancedInvisibilityPlugin plugin;
    private PacketAdapter metadataAdapter;
    private PacketAdapter soundAdapter;

    public PacketListeners(AdvancedInvisibilityPlugin plugin) {
        this.plugin = plugin;
    }

    public void register() {
        // 1. Strip the "on fire" metadata bit
        metadataAdapter = new PacketAdapter(plugin, ListenerPriority.HIGHEST, PacketType.Play.Server.ENTITY_METADATA) {
            @Override
            public void onPacketSending(PacketEvent event) {
                Player receiver = event.getPlayer();
                Entity entity = event.getPacket().getEntityModifier(event).readSafely(0);

                if (entity instanceof Player) {
                    Player target = (Player) entity;
                    if (receiver.equals(target)) return;

                    if (PacketListeners.this.plugin.getEffectManager().hasEffect(target)) {
                        List<WrappedDataValue> dataValues = event.getPacket().getDataValueCollectionModifier().readSafely(0);
                        if (dataValues != null) {
                            List<WrappedDataValue> newValues = new ArrayList<>();
                            boolean changed = false;

                            for (WrappedDataValue value : dataValues) {
                                if (value.getIndex() == 0) { // Entity flags
                                    Object val = value.getValue();
                                    if (val instanceof Byte) {
                                        byte flags = (Byte) val;
                                        if ((flags & 0x01) == 0x01) { // is on fire
                                            flags &= ~0x01;
                                            WrappedDataValue newValue = new WrappedDataValue(value.getIndex(), value.getSerializer(), flags);
                                            newValues.add(newValue);
                                            changed = true;
                                            continue;
                                        }
                                    }
                                }
                                newValues.add(value);
                            }

                            if (changed) {
                                event.getPacket().getDataValueCollectionModifier().write(0, newValues);
                            }
                        }
                    }
                }
            }
        };
        ProtocolLibrary.getProtocolManager().addPacketListener(metadataAdapter);

        // [Experimental] Attempting to remove sounds generated by invisible player
        // 2. Suppress hurt sounds, equip sounds, and burps
        soundAdapter = new PacketAdapter(plugin, ListenerPriority.HIGHEST,
                PacketType.Play.Server.NAMED_SOUND_EFFECT,
                PacketType.Play.Server.ENTITY_SOUND) {
            @Override
            public void onPacketSending(PacketEvent event) {
                Player receiver = event.getPlayer();

                if (event.getPacketType() == PacketType.Play.Server.ENTITY_SOUND) {
                    Entity entity = event.getPacket().getEntityModifier(event).readSafely(0);
                    if (entity instanceof Player) {
                        Player target = (Player) entity;
                        if (!receiver.equals(target) && PacketListeners.this.plugin.getEffectManager().hasEffect(target)) {
                            Sound sound = event.getPacket().getSoundEffects().readSafely(0);
                            if (sound != null) {
                                String name = sound.name();
                                if (name.contains("HURT") || name.contains("DAMAGE") || name.contains("EQUIP") || name.contains("BURP")) {
                                    event.setCancelled(true);
                                }
                            }
                        }
                    }
                } else if (event.getPacketType() == PacketType.Play.Server.NAMED_SOUND_EFFECT) {
                    // Modern versions usually route through ENTITY_SOUND, but just in case:
                }
            }
        };
        ProtocolLibrary.getProtocolManager().addPacketListener(soundAdapter);
    }

    public void unregister() {
        if (metadataAdapter != null) {
            ProtocolLibrary.getProtocolManager().removePacketListener(metadataAdapter);
        }
        if (soundAdapter != null) {
            ProtocolLibrary.getProtocolManager().removePacketListener(soundAdapter);
        }
    }
}
