package com.advanceinv.advancedinvisibility;

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.events.ListenerPriority;
import com.comphenix.protocol.events.PacketAdapter;
import com.comphenix.protocol.events.PacketEvent;
import com.comphenix.protocol.wrappers.WrappedDataValue;
import org.bukkit.Sound;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;

import java.util.ArrayList;
import java.util.List;

public class PacketListeners {

    private final AdvancedInvisibilityPlugin plugin;
    private PacketAdapter metadataAdapter;
    private PacketAdapter soundAdapter;

    public PacketListeners(AdvancedInvisibilityPlugin plugin) {
        this.plugin = plugin;
    }

    public void register() {
        // 1. Strip the "on fire" metadata bit
        metadataAdapter = new PacketAdapter(plugin, ListenerPriority.HIGHEST, PacketType.Play.Server.ENTITY_METADATA) {
            @Override
            public void onPacketSending(PacketEvent event) {
                Player receiver = event.getPlayer();
                Entity entity = event.getPacket().getEntityModifier(event).readSafely(0);

                if (entity instanceof Player) {
                    Player target = (Player) entity;
                    if (receiver.equals(target)) return;
                    
                    // Skip suppression if player is currently in reveal window
                    if (PacketListeners.this.plugin.getEffectManager().isRevealed(target.getUniqueId())) return;

                    if (PacketListeners.this.plugin.getEffectManager().hasEffect(target)) {
                        List<WrappedDataValue> dataValues = event.getPacket().getDataValueCollectionModifier().readSafely(0);
                        if (dataValues != null) {
                            List<WrappedDataValue> newValues = new ArrayList<>();
                            boolean changed = false;

                            for (WrappedDataValue value : dataValues) {
                                if (value.getIndex() == 0) { // Entity flags
                                    Object val = value.getValue();
                                    if (val instanceof Byte) {
                                        byte flags = (Byte) val;
                                        if ((flags & 0x01) == 0x01) { // is on fire
                                            flags &= ~0x01;
                                            WrappedDataValue newValue = new WrappedDataValue(value.getIndex(), value.getSerializer(), flags);
                                            newValues.add(newValue);
                                            changed = true;
                                            continue;
                                        }
                                    }
                                }
                                newValues.add(value);
                            }

                            if (changed) {
                                event.getPacket().getDataValueCollectionModifier().write(0, newValues);
                            }
                        }
                    }
                }
            }
        };
        ProtocolLibrary.getProtocolManager().addPacketListener(metadataAdapter);

        // 2. Suppress sounds generated by invisible player (hurt, equip, eating, drinking, burp)
        // Note: On Paper 1.21+, some sounds route through ENTITY_SOUND, but positional sounds (like armor equip and burp) route through NAMED_SOUND_EFFECT.
        soundAdapter = new PacketAdapter(plugin, ListenerPriority.HIGHEST,
                PacketType.Play.Server.NAMED_SOUND_EFFECT,
                PacketType.Play.Server.ENTITY_SOUND) {
            @Override
            public void onPacketSending(PacketEvent event) {
                Player receiver = event.getPlayer();
                if (event.getPacketType() == PacketType.Play.Server.ENTITY_SOUND) {
                    Entity entity = event.getPacket().getEntityModifier(event).readSafely(0);
                    if (entity instanceof Player) {
                        Player target = (Player) entity;
                        if (receiver.equals(target)) return;

                        // Skip suppression if player is currently in reveal window
                        if (PacketListeners.this.plugin.getEffectManager().isRevealed(target.getUniqueId())) return;

                        if (PacketListeners.this.plugin.getEffectManager().hasEffect(target)) {
                            Sound sound = event.getPacket().getSoundEffects().readSafely(0);
                            if (sound != null && shouldSuppressSound(sound.name())) {
                                event.setCancelled(true);
                            }
                        }
                    }
                } else if (event.getPacketType() == PacketType.Play.Server.NAMED_SOUND_EFFECT) {
                    // ProtocolLib's getSoundEffects() crashes on Paper 1.21.11 for this packet due to WrappedRegistry.
                    // Instead, we read the raw NMS object (Holder<SoundEvent>) and check its toString().
                    Object rawSound = event.getPacket().getModifier().readSafely(0);
                    if (rawSound != null) {
                        String soundStr = rawSound.toString().toUpperCase();
                        if (shouldSuppressSound(soundStr)) {
                            // Check every invisible player to see if they are close to the sound origin
                            for (Player invisible : org.bukkit.Bukkit.getOnlinePlayers()) {
                                if (invisible.equals(receiver)) continue;
                                if (!invisible.getWorld().equals(receiver.getWorld())) continue;
                                if (!PacketListeners.this.plugin.getEffectManager().hasEffect(invisible)) continue;
                                if (PacketListeners.this.plugin.getEffectManager().isRevealed(invisible.getUniqueId())) continue;

                                // Since NAMED_SOUND_EFFECT has a specific structure for coordinates,
                                // we try to read integers 0, 1, 2. If it fails, we ignore it.
                                double x = 0, y = 0, z = 0;
                                try {
                                    x = event.getPacket().getIntegers().readSafely(0) / 8.0;
                                    y = event.getPacket().getIntegers().readSafely(1) / 8.0;
                                    z = event.getPacket().getIntegers().readSafely(2) / 8.0;
                                } catch (Exception ignored) {}
                                
                                org.bukkit.Location soundLoc = new org.bukkit.Location(invisible.getWorld(), x, y, z);
                                if (invisible.getLocation().distanceSquared(soundLoc) < 4.0) { // within ~2 blocks
                                    event.setCancelled(true);
                                    return;
                                }
                            }
                        }
                    }
                }
            }
        };
        ProtocolLibrary.getProtocolManager().addPacketListener(soundAdapter);
    }

    public void unregister() {
        if (metadataAdapter != null) {
            ProtocolLibrary.getProtocolManager().removePacketListener(metadataAdapter);
        }
        if (soundAdapter != null) {
            ProtocolLibrary.getProtocolManager().removePacketListener(soundAdapter);
        }
    }

    /**
     * Returns true if a sound (identified by its Bukkit Sound enum name) should be
     * suppressed for an invisible player.
     *
     * Sound enum names in Bukkit mirror Minecraft's sound event keys with dots
     * replaced by underscores and all uppercase, e.g.:
     *   entity.player.burp  →  ENTITY_PLAYER_BURP
     *   entity.generic.eat  →  ENTITY_GENERIC_EAT
     *   item.armor.equip_iron → ITEM_ARMOR_EQUIP_IRON
     */
    private boolean shouldSuppressSound(String soundName) {
        ConfigManager config = plugin.getConfigManager();

        // Hurt / damage sounds
        if (config.isSuppressHurt() && (soundName.contains("HURT") || soundName.contains("DAMAGE"))) return true;
        // Armor equip sounds
        // Bukkit enum uses underscores: ITEM_ARMOR_EQUIP_DIAMOND
        // NMS raw string uses dots: minecraft:item.armor.equip_diamond
        if (config.isSuppressArmorEquip() && (soundName.contains("ARMOR_EQUIP") || soundName.contains("EQUIP_ARMOR") || soundName.contains("ARMOR.EQUIP"))) return true;
        // Legacy equip keyword for older API versions
        if (config.isSuppressArmorEquip() && (soundName.contains("_EQUIP") || soundName.contains(".EQUIP"))) return true;
        // Consume sounds (eating, drinking, burping)
        if (config.isSuppressConsumeSounds() && (
                soundName.contains("_EAT") || soundName.equals("EAT") ||
                soundName.contains("_DRINK") || soundName.equals("DRINK") ||
                soundName.contains("BURP")
        )) return true;
        // Placing sounds (blocks and water bucket)
        if (config.isSuppressBlockPlace() && (soundName.contains("_PLACE") || soundName.contains(".PLACE") || soundName.contains("BUCKET_EMPTY") || soundName.contains("BUCKET.EMPTY"))) return true;
        // Block break sounds (e.g. block.stone.break → BLOCK_STONE_BREAK)
        if (config.isSuppressBlockBreak() && (soundName.contains("_BREAK") || soundName.contains(".BREAK"))) return true;
        // Block interact sounds: container open/close (chest, barrel, shulker, door, trapdoor, etc.)
        if (config.isSuppressBlockInteract() && (soundName.contains("_OPEN") || soundName.contains(".OPEN") || soundName.contains("_CLOSE") || soundName.contains(".CLOSE"))) return true;

        return false;
    }
}
